//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Game.Content.UI
{
    
    
    public class WindowType
    {
        
        public const string UNDEFINED = "Undefined";
        
        public const string END_GAME_WINDOW = "EndGameWindow";
        
        public const string GAME_FIELD_WINDOW = "GameFieldWindow";
        
        public const string HUD = "HUD";
        
        public const string MAIN_MENU = "MainMenu";
        
        public const string PAUSE_WINDOW = "PauseWindow";
    }
}
